TDL-3
bencerlogas/todo pull request #4
Opened 2022-05-25 08:36 UTC by bencerlogas

2022-05-25 09:18 UTC, kincsokiss commented on src/App.vue
Please remove the <style></style> if it's empty.

2022-05-25 09:18 UTC, kincsokiss commented on src/components/CardText.vue
> +  <h1></h1>
Please remove the unused, empty and commented out code lines from all of the files generally: 
<h1></h1>
//import defineEmits from 'vue';
<style></style>

2022-05-25 09:18 UTC, kincsokiss commented on src/components/CardText.vue
> +console.log(props);
If you use console logs please add meaningful context as well.

2022-05-25 09:18 UTC, kincsokiss commented on src/components/PriorityCheck.vue
> +  <div>asdasd</div>
I think this component is not done :))

2022-05-25 09:50 UTC, bencerlogas commented on src/components/CardText.vue
> +console.log(props);
If i remove the console.log i get an error in terminal, because i'm not using the props anywhere else yet.

2022-05-25 09:50 UTC, bencerlogas commented on src/components/PriorityCheck.vue
> +  <div>asdasd</div>
The components are created generally for the moment, and in another task?(i guess thats how it's called) will be finished.

2022-05-26 06:07 UTC, komaromiGyorgy requested changes

2022-05-26 06:07 UTC, komaromiGyorgy commented on src/components/CardText.vue
> +console.log('CardText Props', props);
remove this unnecessary console log!

2022-05-26 06:07 UTC, komaromiGyorgy commented on src/components/CardTitle.vue
> +console.log('CardText Props', props);
remove this unnecessary console log!

2022-05-26 06:07 UTC, komaromiGyorgy commented on src/components/CheckBox.vue
> +console.log('CardText Props', props);
remove this unnecessary console log!

2022-05-26 06:07 UTC, komaromiGyorgy commented on src/components/GeneralCard.vue
> +console.log(props);
remove this unnecessary console log!

2022-05-26 06:17 UTC, komaromiGyorgy requested changes

2022-05-26 06:17 UTC, komaromiGyorgy commented on src/components/CardText.vue
> +import { defineProps } from 'vue';
remove unnecessary import of defineProps, since it is a compiler macro!
Read more on [defineProps and defineEmits and other compiler macros and script setup]( https://vuejs.org/api/sfc-script-setup.html#defineprops-defineemits)!

2022-05-26 06:17 UTC, komaromiGyorgy commented on src/components/CardText.vue
> +import { defineProps } from 'vue';
Same for every occurence of defineProps or defineEmits

2022-05-26 06:26 UTC, komaromiGyorgy approved these changes

2022-05-26 06:27 UTC, merged