TDL-5
bencerlogas/todo pull request #7
Opened 2022-06-09 10:44 UTC by bencerlogas

2022-06-09 12:43 UTC, kincsokiss requested changes

2022-06-09 12:43 UTC, kincsokiss commented on src/components/GeneralCard.vue
> +function toggleEditmodeOn() {
If you change the name to "setEditModeState" and add the value as a parameter, you can set the isEdit.value at one place only. 

`function setEditModeState(state) {
     isEdited.value = state;
}

function saveTodo() {
 setEditModeState(!isEdited.value)
  emit('priorityvalues', priority.value, props.index);
}
`

2022-06-09 12:43 UTC, kincsokiss commented on src/components/GeneralCard.vue
> +  isEdited.value = false;
Call the "setEditModeState(false)" ( current name: toggleEditmodeOn) instead of isEdited.value = false;

Move that line before the emit();

2022-06-09 12:43 UTC, kincsokiss commented on src/components/PriorityCheck.vue
> +      @click="openDropdown()"
Please rename the openDropdown to openPriorityDropDown, it's more descriptive.

2022-06-09 12:43 UTC, kincsokiss commented on src/components/PriorityCheck.vue
> +defineProps({ isEdited: Boolean, isPriorityCheckClicked: Boolean });
Please add a new line before this in order to be more readable.

2022-06-09 12:43 UTC, kincsokiss commented on src/components/PriorityCheck.vue
> +const isPriorityCheckClicked = ref(true);
Please rename this isPriorityCheckClicked.

2022-06-09 12:43 UTC, kincsokiss commented on src/components/TodoList.vue
> +        @deleteThis="delCard"
Rename the delCard to deleteCard

2022-06-09 12:43 UTC, kincsokiss commented on src/components/TodoList.vue
> +.emptyimg-leave-to {
You can merge .emptyimg-leave-to and .emptyimg-enter-from

2022-06-09 12:56 UTC, gerebdavid commented on src/components/CheckBox.vue
> +      :class="isBtnChecked ? 'border-[#4FDA9B]' : 'border-black'"
Please create a computed for this.

2022-06-09 12:56 UTC, gerebdavid commented on src/components/GeneralCard.vue
> +    :class="priorityCheckClicked ? 'bg-disabled' : ''"
Computed again

2022-06-13 10:15 UTC, kincsokiss requested changes

2022-06-13 10:15 UTC, kincsokiss commented on src/components/TodoList.vue
> +        :key="card"
Please do not se object as a :key value because it will be [object Object]. Use the index or one of the unique item of the card object.

2022-06-13 10:15 UTC, kincsokiss commented on src/components/TodoList.vue
> +        @sendPriorityvalues="pushPriority"
Use camelCase in the  "sendPriorityvalues"

2022-06-13 10:15 UTC, kincsokiss commented on src/components/TodoList.vue
> +function pushPriority(priority, index) {
Rename pushPriority to savePriority. I think it is more descriptive.

2022-06-13 10:15 UTC, kincsokiss commented on src/components/TodoList.vue
> +.empty-img-enter-active {
Please merge the "empty-img-enter-active" and "empty-img-leave-active" because the content is the same:

.empty-img-enter-active, .empty-img-leave-active {
...
}

2022-06-13 10:16 UTC, komaromiGyorgy requested changes

2022-06-29 06:08 UTC, merged